// <auto-generated />
namespace MyFirstAspnetProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Product_Category_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_Category_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "202403131206291_Product_Category_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
